// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZNuW6-8ws9z1uS8TS2p2c4MErPfk7Dp0',
    appId: '1:271200451603:web:8ca291e4cae276f4aed3e6',
    messagingSenderId: '271200451603',
    projectId: 'tstfb-41dcf',
    authDomain: 'tstfb-41dcf.firebaseapp.com',
    storageBucket: 'tstfb-41dcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6gj5JSwjx8HhQ3pkil5_Inh4AWVpHV8o',
    appId: '1:271200451603:android:2de59cb276941426aed3e6',
    messagingSenderId: '271200451603',
    projectId: 'tstfb-41dcf',
    storageBucket: 'tstfb-41dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkScrmGtX_aelbdGHA5ruGRHjLT1DtvQ',
    appId: '1:271200451603:ios:716fb8ad1b096a14aed3e6',
    messagingSenderId: '271200451603',
    projectId: 'tstfb-41dcf',
    storageBucket: 'tstfb-41dcf.firebasestorage.app',
    iosBundleId: 'com.example.wedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXkScrmGtX_aelbdGHA5ruGRHjLT1DtvQ',
    appId: '1:271200451603:ios:716fb8ad1b096a14aed3e6',
    messagingSenderId: '271200451603',
    projectId: 'tstfb-41dcf',
    storageBucket: 'tstfb-41dcf.firebasestorage.app',
    iosBundleId: 'com.example.wedding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZNuW6-8ws9z1uS8TS2p2c4MErPfk7Dp0',
    appId: '1:271200451603:web:10ef9b4d386a7fbfaed3e6',
    messagingSenderId: '271200451603',
    projectId: 'tstfb-41dcf',
    authDomain: 'tstfb-41dcf.firebaseapp.com',
    storageBucket: 'tstfb-41dcf.firebasestorage.app',
  );
}
